name: Regression tests

inputs:
  artifact-name:
    description: 'Name of the uploaded artifact'
    required: false
    default: 'regression-test-results'
  test-config:
    description: 'Path to the test configuration file'
    required: false
    default: 'INCHI-1-TEST/tests/test_library/config/config_regression_linux.py'
  shell:
    description: 'Shell for running the tests'
    required: false
    default: 'bash'

runs:
  using: "composite"
  steps:
    - name: Run regression tests
      run: python INCHI-1-TEST/tests/test_library/inchi_tests/run_tests.py  --test-config=${{ inputs.test-config}} --data-config=INCHI-1-TEST/tests/test_library/config/config_ci.py
      shell: ${{ inputs.shell }}

    - name: Write regression summary
      if: '!cancelled()'
      run: python INCHI-1-TEST/tests/test_library/inchi_tests/parse_log.py  --test-config=${{ inputs.test-config}} --data-config=INCHI-1-TEST/tests/test_library/config/config_ci.py
      shell: ${{ inputs.shell }}

    - name: Upload regression test results
      if: '!cancelled()'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          ./INCHI-1-TEST/tests/test_library/data/ci/*_regression_ci.log
          ./INCHI-1-TEST/tests/test_library/data/ci/*_regression_ci_*.html
