name: Invariance tests

inputs:
  artifact-name:
    description: 'Name of the uploaded artifact'
    required: false
    default: 'invariance-test-results'

runs:
  using: "composite"
  steps:
    - name: Run invariance tests
      run: run-tests --test-config=INCHI-1-TEST/tests/test_library/config/config.invariance.py --data-config=INCHI-1-TEST/tests/test_library/config/config.ci.py
      shell: bash

    - name: Write invariance summary
      if: '!cancelled()'
      run: parse-log --test-config=INCHI-1-TEST/tests/test_library/config/config.invariance.py --data-config=INCHI-1-TEST/tests/test_library/config/config.ci.py
      shell: bash

    - name: Upload invariance test results
      if: '!cancelled()'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          ./INCHI-1-TEST/tests/test_library/data/ci/*_invariance_ci.log
          ./INCHI-1-TEST/tests/test_library/data/ci/*_invariance_ci_*.html
