name: InChI Continuous Integration

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  test_glibc_gcc:
    runs-on: ubuntu-24.04
    container: gcc:14

    steps:
      - uses: actions/checkout@v4

      - name: Install test dependencies
        run: cd INCHI-1-TEST && ./install_test_dependencies.sh

      - name: Install build dependencies
        run: cd INCHI-1-TEST && ./install_build_dependencies.sh

      - id: build_exe
        run: ./INCHI-1-TEST/build_with_cmake.sh exe

      - name: Run executable tests
        if: ${{ !cancelled() && steps.build_exe.outcome == 'success' }}
        run: pytest INCHI-1-TEST/tests/test_executable

      - id: build_lib
        run: ./INCHI-1-TEST/build_with_cmake.sh lib

      - name: Run multithreading test
        if: ${{ !cancelled() && steps.build_lib.outcome == 'success' }}
        run: python INCHI-1-TEST/tests/test_library/test_multithreading.py
        timeout-minutes: 1

      - uses: ./.github/actions/regression_tests
        if: ${{ !cancelled() && steps.build_lib.outcome == 'success' }}
        with:
          artifact-name: regression-test-results_glibc_gcc

      - uses: ./.github/actions/invariance_tests
        if: ${{ !cancelled() && steps.build_lib.outcome == 'success' }}
        with:
          artifact-name: invariance-test-results_glibc_gcc


  test_musl_gcc:
    runs-on: ubuntu-24.04
    container: alpine:latest

    steps:
      - name: Install build and test environment
        run: |
          apk add bash git musl-dev gcc g++ make python3 py-pip cmake

      # We need to install git before checking out the repository.
      # Otherwise, the repository will be downloaded using the GitHub REST API instead of git.
      - uses: actions/checkout@v4

      - name: Show Python version
        run: |
          python --version

      - name: Configure pip to break system packages
        run: |
          mkdir -p ~/.config/pip
          cat <<EOT >> ~/.config/pip/pip.conf
          [global]
          break-system-packages = true
          EOT

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e INCHI-1-TEST

      - id: build_exe
        run: ./INCHI-1-TEST/build_with_cmake.sh exe

      - name: Run executable tests
        if: ${{ !cancelled() && steps.build_exe.outcome == 'success' }}
        run: pytest INCHI-1-TEST/tests/test_executable

      - id: build_lib
        run: ./INCHI-1-TEST/build_with_cmake.sh lib

      - name: Run multithreading test
        if: ${{ !cancelled() && steps.build_lib.outcome == 'success' }}
        run: python INCHI-1-TEST/tests/test_library/test_multithreading.py
        timeout-minutes: 1

      - uses: ./.github/actions/regression_tests
        if: ${{ !cancelled() && steps.build_lib.outcome == 'success' }}
        with:
          artifact-name: regression-test-results_musl_gcc

      # FIXME: We don't run invariance test on alpine yet because of difficulties with RDKit installation.
